title: Nguyễn Thị Huê
tagline: "Hue Nguyen's blog"
description: ""
url: "https://nguyenhue91.github.io"
baseurl: ""
twitter_username:
github_username: nguyenhue91

# Dependencies
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Permalinks
permalink: pretty

author:
  name: NGUYEN THI HUE
  email: 

paginate: 5
paginate_path: "/blog/page:num/"

github:
  repo: https://github.com/nguyenhue91

# Disqus Comments
disqus:
  shortname:

google_analytics: # UA

plugins:
  - jekyll-gist
  - jekyll-octicons
  - jekyll-paginate
  - jemoji

excerpt_separator: <!--more-->
